export const permissions = {
  requested: [
    // STOPPING
    { value: "Yes, you can stop now.", weight: 4 },
    { value: "You’re allowed to be done for today.", weight: 4 },
    { value: "You can leave this unfinished.", weight: 3 },
    { value: "You don’t have to push through.", weight: 3 },
    { value: "It’s okay to stop mid-way.", weight: 3 },
    { value: "You can call it here.", weight: 2 },
    { value: "Stopping is allowed.", weight: 2 },
    { value: "You don’t have to keep going.", weight: 2 },
    { value: "You can pause without a plan.", weight: 1 },
    { value: "You’re allowed to quit this.", weight: 1 },

    // REST
    { value: "You’re allowed to rest.", weight: 4 },
    { value: "You can do nothing right now.", weight: 3 },
    { value: "Rest doesn’t need to be earned.", weight: 3 },
    { value: "You can lie down.", weight: 3 },
    { value: "You’re allowed to take a nap.", weight: 2 },
    { value: "It’s okay to be unproductive today.", weight: 2 },
    { value: "You can take the day off mentally.", weight: 2 },
    { value: "You don’t need to recharge efficiently.", weight: 1 },
    { value: "You can rest even if things aren’t finished.", weight: 1 },
    { value: "You’re allowed to rest longer than planned.", weight: 1 },

    // NO / BOUNDARIES
    { value: "You can say no.", weight: 4 },
    { value: "You don’t have to reply.", weight: 3 },
    { value: "You can cancel.", weight: 3 },
    { value: "You’re allowed to protect your time.", weight: 3 },
    { value: "You don’t owe an explanation.", weight: 2 },
    { value: "You can ignore this.", weight: 2 },
    { value: "You’re allowed to disappoint someone.", weight: 2 },
    { value: "You can choose yourself here.", weight: 2 },
    { value: "You don’t have to be available.", weight: 1 },
    { value: "You’re allowed to withdraw.", weight: 1 },

    // UNCERTAINTY
    { value: "You don’t need to decide yet.", weight: 4 },
    { value: "It’s okay to not know.", weight: 3 },
    { value: "You can wait.", weight: 3 },
    { value: "You don’t have to be sure.", weight: 3 },
    { value: "You’re allowed to change your mind later.", weight: 2 },
    { value: "You can sit with this.", weight: 2 },
    { value: "You don’t need clarity right now.", weight: 2 },
    { value: "You’re allowed to be unsure.", weight: 2 },
    { value: "You can move slowly.", weight: 1 },
    { value: "You don’t need an answer today.", weight: 1 },

    // SELF-TRUST
    { value: "You can trust your judgment.", weight: 3 },
    { value: "You’re allowed to trust yourself.", weight: 3 },
    { value: "You don’t need more input.", weight: 3 },
    { value: "You can ignore that advice.", weight: 2 },
    { value: "You know enough to choose.", weight: 2 },
    { value: "You can go with your instinct.", weight: 2 },
    { value: "You don’t need consensus.", weight: 2 },
    { value: "You’re allowed to decide alone.", weight: 2 },
    { value: "You can stop asking for validation.", weight: 1 },
    { value: "You already know what you want.", weight: 1 },

    // LETTING GO
    { value: "You’re allowed to let this go.", weight: 3 },
    { value: "You can release this.", weight: 3 },
    { value: "You don’t have to carry this anymore.", weight: 3 },
    { value: "You can stop holding onto this.", weight: 2 },
    { value: "You’re allowed to move on.", weight: 2 },
    { value: "You can let this end.", weight: 2 },
    { value: "You don’t need closure.", weight: 2 },
    { value: "You can leave this in the past.", weight: 2 },
    { value: "You’re allowed to outgrow this.", weight: 1 },
    { value: "You can stop trying to fix this.", weight: 1 },

    // ENOUGHNESS
    { value: "You did enough.", weight: 4 },
    { value: "This is enough.", weight: 3 },
    { value: "You are enough.", weight: 3 },
    { value: "You’ve already done your part.", weight: 3 },
    { value: "Nothing more is required.", weight: 2 },
    { value: "You don’t need to do more.", weight: 2 },
    { value: "You’re not behind.", weight: 2 },
    { value: "You don’t need to prove anything.", weight: 2 },
    { value: "What you gave was sufficient.", weight: 1 },
    { value: "You can stop striving now.", weight: 1 },
  ],
  unsolicited: [
    { value: "Nobody is keeping score.", weight: 3 },
    { value: "You’re not behind.", weight: 3 },
    { value: "This isn’t a test.", weight: 3 },
    { value: "Nothing bad is about to happen.", weight: 3 },
    { value: "You’re allowed to exist at this pace.", weight: 3 },

    { value: "You don’t need to justify this.", weight: 2 },
    { value: "This doesn’t define you.", weight: 2 },
    { value: "You haven’t missed your chance.", weight: 2 },
    { value: "You’re not failing quietly.", weight: 2 },
    { value: "You’re allowed to be human here.", weight: 2 },
    { value: "This is harder than it looks.", weight: 2 },
    { value: "You’re doing this without enough rest.", weight: 2 },
    { value: "You’re not broken.", weight: 2 },

    { value: "You don’t need to become someone else.", weight: 1 },
    { value: "It’s okay if this matters to you.", weight: 1 },
    { value: "You’re allowed to care less.", weight: 1 },
    { value: "You’re not late to your own life.", weight: 1 },
    { value: "You don’t need to be impressive.", weight: 1 },
    { value: "This is not the moment everything falls apart.", weight: 1 },
    { value: "You don’t have to make this meaningful.", weight: 1 },
  ],
};
